//
// Created by Orion on 3/4/2022.
//

#ifndef VCL_TEST_DGEMMVECTORBLOCKED2ACCJKI_H
#define VCL_TEST_DGEMMVECTORBLOCKED2ACCJKI_H

#include "DgemmVectorBlocked.h"

#endif //VCL_TEST_DGEMMVECTORBLOCKED2ACCJKI_H
