//
// Created by Serendipity_2 on 2/24/2022.
//

#ifndef VCL_TEST_DGEMMSCALARBLOCKED1ACCIJK_H
#define VCL_TEST_DGEMMSCALARBLOCKED1ACCIJK_H

#include "DgemmBlocked.h"

#endif //VCL_TEST_DGEMMSCALARBLOCKED1ACCIJK_H
