//
// Created by Orion on 2/28/2022.
//

#ifndef VCL_TEST_DGEMMVECTORNONBLOCKEDJKI_H
#define VCL_TEST_DGEMMVECTORNONBLOCKEDJKI_H


#include "DgemmVector.h"

#endif //VCL_TEST_DGEMMVECTORNONBLOCKEDJKI_H
