//
// Created by Orion on 2/28/2022.
//

#ifndef VCL_TEST_DGEMMVECTORBLOCKED1ACCIJK_H
#define VCL_TEST_DGEMMVECTORBLOCKED1ACCIJK_H

#include "DgemmVectorBlocked.h"

#endif //VCL_TEST_DGEMMVECTORBLOCKED1ACCIJK_H
