//
// Created by Orion on 3/4/2022.
//

#ifndef VCL_TEST_DGEMMVECTORNONBLOCKED2ACCIJK_H
#define VCL_TEST_DGEMMVECTORNONBLOCKED2ACCIJK_H

#include "DgemmVector.h"

#endif //VCL_TEST_DGEMMVECTORNONBLOCKED2ACCIJK_H
